import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar/navBar";
import Footer from "./components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="">
          <header className="bg-green-600">
            <div className="container mx-auto">
              <NavBar/>
            </div>
          </header>
        </div>
        {/* Nội dung chính */}
          <main className="">
            {children}
          </main>

          {/* footer */}
          <footer className="w-full bottom-0 h-[319px] bg-green-600">
            <div className="container mx-auto">
              <Footer/>
            </div>
          </footer>
      </body>
    </html>
  );
}
